### ISSUE TITLE
Questions about converting non-root channels to 3 for bandai-namco dataset

### ISSUE THREAD

**Issue by Sarah816** [Wasserwecken/bvhio#15]
Hi @Wasserwecken ! Thanks for the amazing work! 

I'm using your code to process Bandai-Namco-Research-Motion Dataset. The code for changing rest pose works out perfectly. However, when I tried to convert non-root channels from 6 to 3, it seems that discarding positional information for some joints would cause errors in the animation. To be specific, the error occurs at Shoulder_L and Shoulder_R:

<img width="690" alt="截屏2024-05-26 14 46 09" src="https://github.com/Wasserwecken/bvhio/assets/98320245/d64cfc6a-0983-4e8e-9b33-2bbc890f36c8">

I'm using the following code that you've mentioned in another issue:

```
import bvhio
bvh = bvhio.readAsBvh('combat_idle_turn_270_R_001__A373.bvh')
bvh.Root = bvh.Root.Children[0]
for joint, index, depth in bvh.Root.layout():
    joint.Channels = ['Xposition', 'Yposition', 'Zposition'] if joint.Name == "Hips" else []
    joint.Channels.extend(['Zrotation', 'Yrotation', 'Xrotation'])
bvhio.writeBvh('new.bvh', bvh, percision=6)
```

Do you have any idea how to fix this problem? Thank you very much!

**Comment by Wasserwecken** [comment]
Hi, you cannot remove positional information for all joints except for the root joint. It makes sense that the shoulders and probably the neck and legs will create broken animations. These joints need some offset, because the shoulder is not directly connected to the spine.

Positional information can be remove if the joint is directly connected to its parent, such as the lower legs or forearms. Just to validate my theroy, do you have a broken animation file for me?

**Comment by Wasserwecken** [comment]
Sorry my answer was kind of bullshit! I checkout the code and it should work with the bandai namco set.
The only thing that will break if you keep the line `bvh.Root = bvh.Root.Children[0]`. Because in the bandai namco set is the global movement attached to the rrot join. THis information is dropped here. If you want to remove the root joint but keep the motion as it is, try following:

1. Update bvhio to 1.4.0
2. In the gist file, add the line 'root = root.Children[0].clearParent()' before the last line. It should look like this:
    ````py
        # scale to meters
        print('| Correct scale')
        root.RestPose.Scale = 0.012
        root.applyRestposeScale(recursive=True, bake=False, bakeKeyframes=True)
    
        # remove the root joint
        root = root.Children[0].clearParent()
    
        print('| Write file')
        bvhio.writeHierarchy(path=destination, root=root, frameTime=1/30)
    ```

4. Use the second code as it is, but without `bvh.Root = bvh.Root.Children[0]`. It should look like this:
    ```py
    modifyFile('test2.bvh', 'out.bvh')
    print('Done.')
    bvh = bvhio.readAsBvh('out.bvh')
    for joint, index, depth in bvh.Root.layout():
        joint.Channels = ['Xposition', 'Yposition', 'Zposition'] if joint.Name == "Hips" else []
        joint.Channels.extend(['Zrotation', 'Yrotation', 'Xrotation'])
    bvhio.writeBvh('final.bvh', bvh, percision=6)
    ```

**Comment by Sarah816** [comment]
Hi, thank you so much for updating the code! Now the animation remains the same after removing original root joint! But when I'm using the second code to remove positional information for non-root joints, the two shoulder joints still seems to have a wrong position. It's different from the original animation.

<img width="451" alt="截屏2024-05-26 22 30 14" src="https://github.com/Wasserwecken/bvhio/assets/98320245/d9403a2a-b1fc-4d62-a5ea-cef5d0fa2dd7">


Maybe it has something to do with the rotation data of shoulder joints and the Chest joint(their parent)? Actually I'm a little confused, because in most cases removing the abundant position data for non-root joints wouldn't cause difference in the animation. But here it seems the position data for two shoulder joints isn't abundant? Sorry for bothering again.

**Comment by Wasserwecken** [comment]
Can you attach the animation file and your code here? So i can check it out

**Comment by Sarah816** [comment]
Oh I checked the code and realized that I've deleted the part for correcting bone roll, so the chest joint has a 90° rotation. The results are correct now, thank you so much!!

**Comment by Wasserwecken** [comment]
Perfekt! Btw you might want to update the version again (to 1.4.3) otherwise the last frame and restpose will be broken
