### ISSUE TITLE
Converting non- root 6 channels to 3

### ISSUE THREAD

**Issue by dj-kefir-siorbacz** [Wasserwecken/bvhio#5]
Hi @Wasserwecken !
Great repo! Loving it!

I was wandering whether it is possible to change a .bvh having 6 channels for all joints to an equivalent one having only 3 channels (only rotations) for all non-root joints.

Tbh I couldn't find any documentation on how parsers parse such .bvh and I would love to know! Are extra positions modifying poses each keyframe?

I know MotionBuilder can do it, but i don't want to rely on it :)

**Comment by dj-kefir-siorbacz** [comment]
Blender, I assume! will struggle as its .bvh import/export is weak

**Comment by dj-kefir-siorbacz** [comment]
Hi @Wasserwecken ! 

Yeah, I know this documentation. The problem is that it says: `I have never encountered a BVH file that didn't have 6 channels for the root object and 3 channels for every other object in the hierarchy.`, so it is of no help to my query :D 

Maybe I wasn't specific enough in my question. I have a .bvh like [this](https://drive.google.com/file/d/1RQsSo2G3TWt05w2kVpCjnKb23J38cmqN/view?usp=sharing). It contains positional info in HIERARCHY for each joint (so 6 channels for every joint). 
The problem is that some .bvh parsers (maybe you're familiar with deep learning 3D animation research? then you might have stumbled upon custom parsers people've written :D) can't read this kind of 6 channels info. Therefore I was thinking if `bvhio` could convert it to the standard format of 6 channels for root and 3 channels for child joints. This conversion would be lossless in the case of my .bvh as the extra positional channels are redundant.

```If a position is given for a child joint, this will move the joint relative to its parent. This is used in the rest pose usually for upper leg and upper arm joints because they are not connected "directly" to the spine. If you set the positions in the keyframe data, this counts as offset to the rest pose positon.```
So the `?position` channels in non-root keyframes are used for something like bendy bones? i.e. when you want to change the length of bones during animation?

**Comment by Wasserwecken** [comment]
Ah okay, you want to clean or modify the animation data, This exaclty the case I have written this libary for. I think this is the snipped youre looking for:

``` py
import bvhio

bvh = bvhio.readAsBvh('C:/Users/ericd/Downloads/combat_idle_turn_270_R_001__A373.bvh')

for joint, index, depth in bvh.Root.layout():
    if "Hips" not in joint.Name:
        joint.Channels = [channel for channel in joint.Channels if 'position' not in channel]

bvhio.writeBvh('C:/Users/ericd/Downloads/new.bvh', bvh, percision=6)
```

This code will !discard! any positional information. If you have animation positions then you have to do more in order to preserve the original motion. You can look into these snippets if you want to modify the rest pose or the animation data:
- https://gist.github.com/Wasserwecken/58ae6579be8ac43508b9b347956afc9a
- https://gist.github.com/Wasserwecken/0802f3a678931e8408f7b78ecb99b00a

`So the ?position channels in non-root keyframes are used for something like bendy bones? i.e. when you want to change the length of bones during animation?`

If you look closer to the snipped you will notice that any positional channel are excluded except for the hips ('if "Hips" not in joint.Name:'). This is because the hips will actually translate to space for the aimation. The rest pose will set the default position for the hip, and the animation data will offset the hip bone. Combined together (restpose + animation) they will result in the correct position.

This behaviour is the same for any other positional information too. I dont know any use case for this, but you could set positional animation data for the upper legs joint to slim or widen the hips. "Bendy"-bones might not be possible with this, but you could "scale" the bones.

**Comment by dj-kefir-siorbacz** [comment]
I see, thanks! 

So positional info. is discarded, but original motions is not preserved : (

**Comment by Wasserwecken** [comment]
`So positional info. is discarded, but original motions is not preserved : (`

If there is no positional animation, then the original motion is preserved!
This is the common case in 99%. So youre good to go :)
